# Generated by Django 5.0.3 on 2024-03-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testarea', '0002_alter_invoicemaster_invoice_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemaster',
            name='invoice_image',
            field=models.ImageField(null=True, upload_to='invoice_image'),
        ),
    ]
