# Generated by Django 5.0.3 on 2024-03-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testarea', '0003_alter_invoicemaster_invoice_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicemaster',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='invoicemaster',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='invoicemaster',
            name='invoice_image',
        ),
        migrations.RemoveField(
            model_name='invoicemaster',
            name='invoice_total',
        ),
        migrations.RemoveField(
            model_name='invoicemaster',
            name='modified_date',
        ),
    ]
