# Generated by Django 5.0.3 on 2024-03-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testarea', '0004_remove_invoicemaster_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemaster',
            name='invoice_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
