# Generated by Django 5.0.3 on 2024-03-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testarea', '0005_alter_invoicemaster_invoice_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemaster',
            name='invoice_desc',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicemaster',
            name='invoice_no',
            field=models.IntegerField(),
        ),
    ]
