# Generated by Django 5.0.3 on 2024-03-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_fooditem_cart_produc_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='produc_item',
            new_name='product_item',
        ),
    ]
