# Generated by Django 5.0.4 on 2024-06-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0003_payment_paypal_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=30),
        ),
    ]
