# Generated by Django 5.0.3 on 2024-03-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_module', '0005_poly1project_poly1artproject_poly1researchproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
