# Generated by Django 5.0.4 on 2024-06-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_module', '0006_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poly1project',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='poly1researchproject',
            name='poly1project_ptr',
        ),
        migrations.DeleteModel(
            name='poly1ArtProject',
        ),
        migrations.DeleteModel(
            name='poly1Project',
        ),
        migrations.DeleteModel(
            name='poly1ResearchProject',
        ),
    ]
